version: "3.9"
services:
  app:
    build: ./infra/php
    container_name: laravel_app
    volumes:
      - ./backend:/data

  back:
    image: nginx:1.20-alpine
    container_name: laravel_web
    volumes:
      - ./backend:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 10082:80
    working_dir: /data

  db:
    build: ./infra/mysql
    container_name: db_app
    volumes:
      - db-store:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=phper
      - PMA_PASSWORD=secret
    ports:
      - "8080:80"

  front:
    build:
      context: ./infra/node
    container_name: react_app
    volumes:
      - ./frontend:/app
    tty: true
    command: sh -c "npm start"
    ports:
      - "3000:3000"

volumes:
  db-store:
